### ISSUE TITLE
src/hfsfuse.c:31:10: fatal error: 'fuse/fuse.h' file not found

### ISSUE THREAD

**Issue by MariaLavrovskaya** [0x09/hfsfuse#10]
Have pulled the very last version, and yet I am still facing this issue: `src/hfsfuse.c:31:10: fatal error: 'fuse/fuse.h' file` not found when trying to build

**Comment by 0x09** [comment]
Hi @MariaLavrovskaya, what OS or distro are you building for?

**Comment by gertjandemulder** [comment]
I'm having the same issue (Mac OSX Catalina 10.15.5)
```
Makefile:79: Warning: git repo nor prepackaged version.h found, hfsfuse will be built without version information
cc -Wall -Wextra -pedantic -Wno-gnu-zero-variadic-macro-arguments -Wno-unused-parameter -Wno-missing-field-initializers -Wno-missing-braces -DFUSE_USE_VERSION=28 -D_FILE_OFFSET_BITS=64 -I/usr/local/include/osxfuse -I /Users/gertjandm/Downloads/hfsfuse-master/lib -O3 -std=gnu11  -DHFSFUSE_VERSION_STRING=\"omitted\" -c -o src/hfsfuse.o src/hfsfuse.c
src/hfsfuse.c:31:10: fatal error: 'fuse/fuse.h' file not found
#include <fuse/fuse.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [src/hfsfuse.o] Error 1
```

**Comment by 0x09** [comment]
@gertjandemulder I'm not sure if this is an issue with the OS detection or your FUSE installation -- if you have [FUSE for macOS](https://osxfuse.github.io) installed already, can you post the output of the `uname` command as well as whether either of the following folders exist?
`/usr/local/include/osxfuse`
`/usr/local/include/fuse`
Thanks.

**Comment by gertjandemulder** [comment]
@0x09 , Fuse wasn't installed yet on this machine 😅 . It's working now !

**Comment by 0x09** [comment]
@gertjandemulder great! I'm actually in the process of restructuring the README with more explicit information about where to install FUSE on each supported platform, since right now this is mainly an exercise for the reader.

**Comment by finaldiner** [comment]
Hi,

Apologies if this is the wrong place for this post but I'm new here and I really don't understand anything about GitHub or coding. I'm just trying to access a Mac HFS+ volume in Catalina using hfsfuse. I get the following errors...

meljefferson@iMac ~ % cd /Users/meljefferson/Downloads/hfsfuse-master
meljefferson@iMac hfsfuse-master % make config WITH_UBILIO=local WITH_UTF8PROC=local
Makefile:87: Warning: git repo nor prepackaged version.h found, hfsfuse will be built without version information
echo "$CONFIG" > config.mak
meljefferson@iMac hfsfuse-master % make
Makefile:87: Warning: git repo nor prepackaged version.h found, hfsfuse will be built without version information
/Library/Developer/CommandLineTools/usr/bin/make -C lib/libhfsuser/
make[1]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C lib/libhfs/
make[1]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C lib/ublio/
make[1]: `libublio.a' is up to date.
/Library/Developer/CommandLineTools/usr/bin/make -C lib/utf8proc/
make[1]: Nothing to be done for `all'.
cc -D_FILE_OFFSET_BITS=64 -O3 -std=gnu11       -DHFSFUSE_VERSION_STRING=\"omitted\"  -o hfsfuse src/hfsfuse.o lib/libhfsuser/libhfsuser.a lib/libhfs/libhfs.a lib/ublio/libublio.a lib/utf8proc/libutf8proc.a -losxfuse -lpthread
ld: library not found for -losxfuse
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hfsfuse] Error 1
meljefferson@iMac hfsfuse-master % make install
Makefile:87: Warning: git repo nor prepackaged version.h found, hfsfuse will be built without version information
/Library/Developer/CommandLineTools/usr/bin/make -C lib/libhfsuser/
make[1]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C lib/libhfs/
make[1]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C lib/ublio/
make[1]: `libublio.a' is up to date.
/Library/Developer/CommandLineTools/usr/bin/make -C lib/utf8proc/
make[1]: Nothing to be done for `all'.
cc -D_FILE_OFFSET_BITS=64 -O3 -std=gnu11       -DHFSFUSE_VERSION_STRING=\"omitted\"  -o hfsfuse src/hfsfuse.o lib/libhfsuser/libhfsuser.a lib/libhfs/libhfs.a lib/ublio/libublio.a lib/utf8proc/libutf8proc.a -losxfuse -lpthread
ld: library not found for -losxfuse
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hfsfuse] Error 1

As far as I can see, Fuse is installed (/usr/local/include/fuse exists). Can anyone explain what my problem may be (in words on one syllable, please)?

**Comment by 0x09** [comment]
Hi @finaldiner, thanks for reporting that -- this is fixed if you pull/download the latest commit https://github.com/0x09/hfsfuse/commit/c7e10ea8f2133abc40123e15cd409597998a0335

**Comment by morgant** [comment]
I just built hfsfuse on OpenBSD 6.8-stable and ran into the `fatal error: 'fuse/fuse.h' file not found` error, as well. On OpenBSD, only `<fuse.h>` is required and it builds and runs well otherwise.

What is your preferred method of adding OpenBSD support for this header include?

**Comment by 0x09** [comment]
@morgant `<fuse.h>` seems preferable anyway since most FUSE libs provide it for compatibility, and those that don't (haiku, openindiana) can be dealt with by adjusting CFLAGS (whereas the inverse is not true.)
I have uncommitted changes switching this as part of some other compatibility work, so I'll just push those.

**Comment by morgant** [comment]
@0x09 Thanks!
