### ISSUE TITLE
make config fails with errors under macOS Big Sur

### ISSUE THREAD

**Issue by oliveratgithub** [0x09/hfsfuse#14]
Trying to make and install hfsfuse under **macOS Big Sur 11.0** (Beta 20A5395g) fails:

* Executing…
```
make config WITH_UBILIO=local WITH_UTF8PROC=localmakemake install
```

* …fails with the following errors
```
Undefined symbols for architecture x86_64:
  "_utf8proc_decompose_char", referenced from:
      _hfs_pathname_from_unix in libhfsuser.a(hfsuser.o)
  "_utf8proc_get_property", referenced from:
      _hfs_pathname_from_unix in libhfsuser.a(hfsuser.o)
  "_utf8proc_iterate", referenced from:
      _hfs_pathname_from_unix in libhfsuser.a(hfsuser.o)
  "_utf8proc_reencode", referenced from:
      _hfs_pathname_from_unix in libhfsuser.a(hfsuser.o)
  "_utf8proc_version", referenced from:
      _hfs_lib_utf8proc_version in libhfsuser.a(features.o)
     (maybe you meant: _hfs_lib_utf8proc_version)
```

```
ld: symbol(s) not found for architecture x86_64
```

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
make: *** [hfsfuse] Error 1
```

Any ideas if this can be fixed within the current release, or needs an update to work under macOS Big Sur explicitely?

Thanks!

**Comment by freemansion** [comment]
same here on Catalina

**Comment by 0x09** [comment]
@oliveratgithub I just pushed a change which makes it clearer what's going on here:
```shell
$ make config WITH_UBILIO=local WITH_UTF8PROC=localmakemake install
Makefile:77: *** Invalid option "localmakemake" for WITH_UTF8PROC. Use one of: none, system, local.  Stop.
```
`make config WITH_UBILIO=local WITH_UTF8PROC=local`,`make`, and `make install` are all separate commands which you have together on one line.
However if you just want to build and install hfsfuse with the default configuration, you can get the same effect by just running `make install`.

**Comment by oliveratgithub** [comment]
> However if you just want to build and install hfsfuse with the default configuration, you can get the same effect by just running `make install`.

@0x09 thanks an I am sorry - clearly a copy Paste mistake on my end – somehow I didn’t notice the concenated `=localmakemake` 🙈
