### ISSUE TITLE
Doesn't find system libutf8proc on OpenBSD 6.8

### ISSUE THREAD

**Issue by morgant** [0x09/hfsfuse#18]
OpenBSD 6.8 has libutf8proc in ports, but when building with `gmake WITH_UTF8PROC=system`, it fails with the following error:

```
In file included from features.c:25:                                                                                                                           
/home/linetrace/Projects/hfsfuse/lib/libhfsuser/features.h:5:10: fatal error: 'utf8proc.h' file not found
#include "utf8proc.h"
         ^~~~~~~~~~~~
```

**Comment by 0x09** [comment]
Closed with https://github.com/0x09/hfsfuse/pull/19

**Comment by 0x09** [comment]
@morgant thanks again, just pushed 0.120 with these changes https://github.com/0x09/hfsfuse/releases/tag/0.120
