### ISSUE TITLE
Fails to compile under ubuntu 16.04

### ISSUE THREAD

**Issue by gilbahat** [0x09/hfsfuse#2]
I cannot compile this on a vanilla ubuntu 16.04. I'm getting the following errors:

cc -O3 -std=gnu11 -DFUSE_USE_VERSION=28 -D_FILE_OFFSET_BITS=64 -DHAVE_UBLIO -DHAVE_UTF8PROC -Ilib/libhfs/ -Ilib/ublio -I/usr/include/fuse -c -o src/hfsfuse.o src/hfsfuse.c
cc -O3 -std=gnu11 -lfuse -lrt -ldl -o hfsfuse lib/libhfs/*.o lib/libhfs/libhfs.a lib/ublio/ublio.o lib/utf8proc/utf8proc.o src/hfslib.o src/hfsfuse.o -lpthread
src/hfshuse.o: In function `hfsfuse_statfs`:
hfsfuse.c:(.text+0x5): undefined reference to `fuse_get_context`

and also in main, undefined reference to `fuse-_main_real`

adding more libs and include paths didn't help, as you can see.

**Comment by 0x09** [comment]
This is a result of libfuse not being listed after the object files, and should be fixed now. Can you pull and try again?

**Comment by gilbahat** [comment]
compiles wonderfully now, thanks!

**Comment by 0x09** [comment]
Great! Thanks for reporting. I had to fix the same problem with resdet and forgot to do it here.
