### ISSUE TITLE
kext load failed

### ISSUE THREAD

**Issue by dave-kennedy** [0x09/hfsfuse#22]
The program threw an error when I tried to run it:

```
$ sudo ./hfsfuse --force -o noatime /dev/disk2s2 ~/iPod
kext load failed: -603947007
mount_osxfuse: the file system is not available (255)
```

Here's the result of `make config`:

```
HAVE_BEXXTOH_ENDIAN_H: no
HAVE_BEXXTOH_SYS_ENDIAN_H: no
HAVE_OSBYTEORDER_H: yes
HAVE_BIRTHTIME: yes
HAVE_STAT_FLAGS: yes
HAVE_STAT_BLKSIZE: yes
HAVE_STAT_BLOCKS: yes
HAVE_VSYSLOG: yes
HAVE_PREAD: yes
```

There was one warning in the `make` output, though I'm not sure if it's relevant:

```
/Library/Developer/CommandLineTools/usr/bin/make -C lib/utf8proc/
cc  -D_FILE_OFFSET_BITS=64 -O3 -std=gnu11   -DHAVE_OSBYTEORDER_H -DHAVE_BIRTHTIME -DHAVE_STAT_FLAGS -DHAVE_STAT_BLKSIZE -DHAVE_STAT_BLOCKS -DHAVE_VSYSLOG -DHAVE_PREAD -DUTF8PROC_EXPORTS -DHFSFUSE_VERSION_STRING=\"0.153-0c63f43\" -fPIC -std=c99 -Wsign-conversion -Wall -Wextra -pedantic -DUTF8PROC_EXPORTS  -c -o utf8proc.o utf8proc.c
utf8proc.c:413:36: warning: implicit conversion changes signedness: 'const utf8proc_propval_t' (aka 'const short') to 'utf8proc_category_t' [-Wsign-conversion]
  return utf8proc_get_property(c)->category;
```

Let me know if you might need any other info to diagnose.

**Comment by 0x09** [comment]
@dave-kennedy that appears to be an issue with your macFUSE installation. It looks like there are some instructions to resolve it here https://github.com/osxfuse/osxfuse/issues/741

**Comment by dave-kennedy** [comment]
What is macFUSE? I had no idea I needed that 😕

**Comment by 0x09** [comment]
@dave-kennedy definitely. I've been drafting a rewrite of the README with more details (including all of the supported FUSE implementations) since the last group of commits, as platform support has been expanded greatly to include other BSDs and Windows for the non-FUSE parts. I'll just keep this open until then.

**Comment by 0x09** [comment]
Closing as more detailed dependency info was added along with several other improvements in  https://github.com/0x09/hfsfuse/commit/c1fa168da6b0ebd59c410019526aee2a75a83d64
