### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by priyadarshan** [0x09/hfsfuse#7]
Thank you for hfsfuse, it is so useful to be able to read directly HFS+ drives.
Would it be possible to have a FreeBSD port for hfsfuse?
It would help a lot inexperienced users (like myself) to install it.

**Comment by 0x09** [comment]
Unfortunately I no longer run FreeBSD day to day and wouldn't be able to maintain the port itself, but I would love for it to be in the ports tree if there were a maintainer. It was written in a way that should be easy to create a port makefile for, and I'm still committed to maintaining compatibility. Feel free to add it to the list at https://wiki.freebsd.org/WantedPorts

**Comment by priyadarshan** [comment]
Thank you so much, I will add it to that page and report back.

**Comment by priyadarshan** [comment]
I am having problmes editing the wiki page. For now, I have posted [here](https://forums.freebsd.org/threads/64200/).

**Comment by priyadarshan** [comment]
The port has been created by tobik (at) FreeBSD.org: https://www.freshports.org/sysutils/fusefs-hfsfuse

**Comment by 0x09** [comment]
Awesome! Thank you for bringing this to the attention of the developers. Since making it possible to mount HFS+ disks on FreeBSD was the impetus for this project, the fact that it's available as a port and easy to find and use out of the box means a lot! Thanks again.
